format output messages

diff --git a/.github/workflows/scheduled-azure-build-and-deploy.yml b/.github/workflows/scheduled-azure-build-and-deploy.yml
--- a/.github/workflows/scheduled-azure-build-and-deploy.yml
+++ b/.github/workflows/scheduled-azure-build-and-deploy.yml
@@ -152,17 +152,21 @@ jobs:
 
     - name: Check for success
       run: |
+        green='\033[0;32m'
+        red='\e[1;31m'
+        clear='\033[0m'
+
         if [[ "${{ steps.azd_provision.outcome }}" == 'success' ]]; then
-          echo "TF Apply SUCCESS"
+          printf "AZD provision ${green}success${clear}"
         else
-          echo "TF Apply failed"
+          printf "AZD provision ${red}failed${clear}"
           exit 1
         fi
         
         if [[ "${{ steps.azd_deploy.outcome }}" == 'success' ]]; then
-          echo "azd deploy SUCCESS"
+          printf "AZD deploy ${green}success${clear}"
         else
-          echo "azd deploy failed"
-          exit 2
+          printf "AZD deploy ${red}failed${clear}"
+          exit 1
         fi
         
